package com.dxh.retail.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TempShare implements Serializable {
    /**
	*记录ID<br/>
	**/
    private Long id;

    /**
	*所属商家ID<br/>
	**/
    private Long vendorId;

    /**
	*单据号<br/>
	**/
    private String orderNo;

    /**
	*分摊金额<br/>
	**/
    private BigDecimal shareAmount;

    /**
	*促销单号<br/>
	**/
    private String sorderNo;

    /**
	*促销名称<br/>
	**/
    private String sorderName;

    /**
	*优惠券号<br/>
	**/
    private String couponNo;

    /**
	*优惠券名称<br/>
	**/
    private String couponName;

    /**
	*分摊类型 【0：优惠券分摊、1：满减分摊、2：组合商品分摊、3：抹零分摊】<br/>
	**/
    private Integer shareType;

    /**
	*是否已完成分摊  【1：完成、 0：未完成】<br/>
	**/
    private Integer shareFlag;

    /**
	*是否已删除  【1：删除、 0：正常】<br/>
	**/
    private Integer df;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tempshare
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("所属商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("单据号")
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    @Lable("分摊金额")
    public BigDecimal getShareAmount() {
        return shareAmount;
    }

    public void setShareAmount(BigDecimal shareAmount) {
        this.shareAmount = shareAmount;
    }

    @Lable("促销单号")
    public String getSorderNo() {
        return sorderNo;
    }

    public void setSorderNo(String sorderNo) {
        this.sorderNo = sorderNo == null ? null : sorderNo.trim();
    }

    @Lable("促销名称")
    public String getSorderName() {
        return sorderName;
    }

    public void setSorderName(String sorderName) {
        this.sorderName = sorderName == null ? null : sorderName.trim();
    }

    @Lable("优惠券号")
    public String getCouponNo() {
        return couponNo;
    }

    public void setCouponNo(String couponNo) {
        this.couponNo = couponNo == null ? null : couponNo.trim();
    }

    @Lable("优惠券名称")
    public String getCouponName() {
        return couponName;
    }

    public void setCouponName(String couponName) {
        this.couponName = couponName == null ? null : couponName.trim();
    }

    @Lable("分摊类型 【0：优惠券分摊、1：满减分摊、2：组合商品分摊、3：抹零分摊】")
    public Integer getShareType() {
        return shareType;
    }

    public void setShareType(Integer shareType) {
        this.shareType = shareType;
    }

    @Lable("是否已完成分摊  【1：完成、 0：未完成】")
    public Integer getShareFlag() {
        return shareFlag;
    }

    public void setShareFlag(Integer shareFlag) {
        this.shareFlag = shareFlag;
    }

    @Lable("是否已删除  【1：删除、 0：正常】")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}