package com.dxh.retail.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TempSaleProm implements Serializable {
    /**
	*记录ID<br/>
	**/
    private Long id;

    /**
	*商家ID<br/>
	**/
    private Long vendorId;

    /**
	*销售单号<br/>
	**/
    private String orderNo;

    /**
	*saledetail商品明细Id<br/>
	**/
    private Long saleDetailId;

    /**
	*该次分摊依赖的数据来源id(暂时只可能是saleProm表或saleDetail表)<br/>
	**/
    private Long sourceId;

    /**
	*该次分摊依赖表【0：saleProm表、1：saleDetail】<br/>
	**/
    private Integer sourceTable;

    /**
	*促销单号<br/>
	**/
    private String sorderNo;

    /**
	*促销名称<br/>
	**/
    private String sorderName;

    /**
	*原价<br/>
	**/
    private BigDecimal salePrice;

    /**
	*促销价<br/>
	**/
    private BigDecimal realPrice;

    /**
	*分摊前价格<br/>
	**/
    private BigDecimal preSharePrice;

    /**
	*分摊后价格<br/>
	**/
    private BigDecimal postSharePrice;

    /**
	*让利金额(如果是分摊的话为分摊金额)<br/>
	**/
    private BigDecimal promAmount;

    /**
	*促销模式 【0：加价购、 1：进价单 、2：特价、 3：折扣、4：满减分摊、5：满送、6：抽奖、7：DM促销、8：组合商品分摊 、9：超额超量促销 、10：联营商品扣率促销单、11：抹零分摊】<br/>
	**/
    private Integer promMode;

    /**
	*促销对象【0：整单、1：单品】<br/>
	**/
    private Integer promTarget;

    /**
	*是否已删除【1：删除、0：正常】<br/>
	**/
    private Integer df;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
	*原saleprom表id<br/>
	**/
    private Long oldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tempsaleprom
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("销售单号")
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    @Lable("saledetail商品明细Id")
    public Long getSaleDetailId() {
        return saleDetailId;
    }

    public void setSaleDetailId(Long saleDetailId) {
        this.saleDetailId = saleDetailId;
    }

    @Lable("该次分摊依赖的数据来源id(暂时只可能是saleProm表或saleDetail表)")
    public Long getSourceId() {
        return sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    @Lable("该次分摊依赖表【0：saleProm表、1：saleDetail】")
    public Integer getSourceTable() {
        return sourceTable;
    }

    public void setSourceTable(Integer sourceTable) {
        this.sourceTable = sourceTable;
    }

    @Lable("促销单号")
    public String getSorderNo() {
        return sorderNo;
    }

    public void setSorderNo(String sorderNo) {
        this.sorderNo = sorderNo == null ? null : sorderNo.trim();
    }

    @Lable("促销名称")
    public String getSorderName() {
        return sorderName;
    }

    public void setSorderName(String sorderName) {
        this.sorderName = sorderName == null ? null : sorderName.trim();
    }

    @Lable("原价")
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    @Lable("促销价")
    public BigDecimal getRealPrice() {
        return realPrice;
    }

    public void setRealPrice(BigDecimal realPrice) {
        this.realPrice = realPrice;
    }

    @Lable("分摊前价格")
    public BigDecimal getPreSharePrice() {
        return preSharePrice;
    }

    public void setPreSharePrice(BigDecimal preSharePrice) {
        this.preSharePrice = preSharePrice;
    }

    @Lable("分摊后价格")
    public BigDecimal getPostSharePrice() {
        return postSharePrice;
    }

    public void setPostSharePrice(BigDecimal postSharePrice) {
        this.postSharePrice = postSharePrice;
    }

    @Lable("让利金额(如果是分摊的话为分摊金额)")
    public BigDecimal getPromAmount() {
        return promAmount;
    }

    public void setPromAmount(BigDecimal promAmount) {
        this.promAmount = promAmount;
    }

    @Lable("促销模式 【0：加价购、 1：进价单 、2：特价、 3：折扣、4：满减分摊、5：满送、6：抽奖、7：DM促销、8：组合商品分摊 、9：超额超量促销 、10：联营商品扣率促销单、11：抹零分摊】")
    public Integer getPromMode() {
        return promMode;
    }

    public void setPromMode(Integer promMode) {
        this.promMode = promMode;
    }

    @Lable("促销对象【0：整单、1：单品】")
    public Integer getPromTarget() {
        return promTarget;
    }

    public void setPromTarget(Integer promTarget) {
        this.promTarget = promTarget;
    }

    @Lable("是否已删除【1：删除、0：正常】")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Lable("原saleprom表id")
    public Long getOldId() {
        return oldId;
    }

    public void setOldId(Long oldId) {
        this.oldId = oldId;
    }
}