package com.dxh.pay.mapper;

import com.dxh.pay.entity.AssetAccount;

public interface AssetAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetaccount
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    int insert(AssetAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetaccount
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    int insertSelective(AssetAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetaccount
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    AssetAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetaccount
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AssetAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assetaccount
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    int updateByPrimaryKey(AssetAccount record);
}