package com.dxh.pay.mapper;

import com.dxh.pay.entity.VendorPartnerSetting;

public interface VendorPartnerSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendorpartnersetting
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    int insert(VendorPartnerSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendorpartnersetting
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    int insertSelective(VendorPartnerSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendorpartnersetting
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    VendorPartnerSetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendorpartnersetting
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(VendorPartnerSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendorpartnersetting
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    int updateByPrimaryKey(VendorPartnerSetting record);
}