package com.dxh.base.mapper;

import com.dxh.base.entity.ThirdUploadData;
import com.dxh.base.entity.ThirdUploadDataWithBLOBs;

public interface ThirdUploadDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduploaddata
     *
     * @mbggenerated Sat Sep 26 10:31:21 GMT+08:00 2020
     */
    int insert(ThirdUploadDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduploaddata
     *
     * @mbggenerated Sat Sep 26 10:31:21 GMT+08:00 2020
     */
    int insertSelective(ThirdUploadDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduploaddata
     *
     * @mbggenerated Sat Sep 26 10:31:21 GMT+08:00 2020
     */
    ThirdUploadDataWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduploaddata
     *
     * @mbggenerated Sat Sep 26 10:31:21 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ThirdUploadDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduploaddata
     *
     * @mbggenerated Sat Sep 26 10:31:21 GMT+08:00 2020
     */
    int updateByPrimaryKeyWithBLOBs(ThirdUploadDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirduploaddata
     *
     * @mbggenerated Sat Sep 26 10:31:21 GMT+08:00 2020
     */
    int updateByPrimaryKey(ThirdUploadData record);
}