package com.dxh.wd.mapper;

import com.dxh.wd.entity.ThirdStoreBind;

public interface ThirdStoreBindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdstorebind
     *
     * @mbggenerated Fri Oct 16 14:19:37 GMT+08:00 2020
     */
    int insert(ThirdStoreBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdstorebind
     *
     * @mbggenerated Fri Oct 16 14:19:37 GMT+08:00 2020
     */
    int insertSelective(ThirdStoreBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdstorebind
     *
     * @mbggenerated Fri Oct 16 14:19:37 GMT+08:00 2020
     */
    ThirdStoreBind selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdstorebind
     *
     * @mbggenerated Fri Oct 16 14:19:37 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ThirdStoreBind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thirdstorebind
     *
     * @mbggenerated Fri Oct 16 14:19:37 GMT+08:00 2020
     */
    int updateByPrimaryKey(ThirdStoreBind record);
}