package com.dxh.retail.mapper;

import com.dxh.retail.entity.TempSaleOrder;

public interface TempSaleOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleorder
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int insert(TempSaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleorder
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int insertSelective(TempSaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleorder
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    TempSaleOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleorder
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TempSaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleorder
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int updateByPrimaryKey(TempSaleOrder record);
}