package com.dxh.retail.mapper;

import com.dxh.retail.entity.TempShare;

public interface TempShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempshare
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int insert(TempShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempshare
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int insertSelective(TempShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempshare
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    TempShare selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempshare
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TempShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempshare
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int updateByPrimaryKey(TempShare record);
}