package com.dxh.retail.mapper;

import com.dxh.retail.entity.TempSaleProm;

public interface TempSalePromMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleprom
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int insert(TempSaleProm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleprom
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int insertSelective(TempSaleProm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleprom
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    TempSaleProm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleprom
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TempSaleProm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempsaleprom
     *
     * @mbggenerated Wed Aug 12 14:27:33 GMT+08:00 2020
     */
    int updateByPrimaryKey(TempSaleProm record);
}