package com.dxh.erp.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class AdrSortingLog implements Serializable {
    /**
	*记录ID<br/>
	**/
    private Long id;

    /**
	*所属商家ID<br/>
	**/
    private Long vendorId;

    /**
	*单据编号<br/>
	**/
    private String orderNo;

    /**
	*操作类型 0-领取任务 1分拣完成 9-释放任务<br/>
	**/
    private Integer actionType;

    /**
	*手持终端编码<br/>
	**/
    private String posCode;

    /**
	*备注<br/>
	**/
    private String memo;

    /**
	*是否已删除1删除 0正常<br/>
	**/
    private Integer df;

    /**
	*操作人<br/>
	**/
    private String creator;

    /**
	*操作时间<br/>
	**/
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adrsortinglog
     *
     * @mbggenerated Tue Oct 22 15:53:02 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("所属商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("单据编号")
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    @Lable("操作类型 0-领取任务 1分拣完成 9-释放任务")
    public Integer getActionType() {
        return actionType;
    }

    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }

    @Lable("手持终端编码")
    public String getPosCode() {
        return posCode;
    }

    public void setPosCode(String posCode) {
        this.posCode = posCode == null ? null : posCode.trim();
    }

    @Lable("备注")
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    @Lable("是否已删除1删除 0正常")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("操作人")
    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    @Lable("操作时间")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}