package com.dxh.erp.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class GxsPurchOrderInfo implements Serializable {
    /**
	*记录编号<br/>
	**/
    private Long id;

    /**
	*所属商家ID<br/>
	**/
    private Long vendorId;

    /**
	*单据编号<br/>
	**/
    private String orderNo;

    /**
	*渠道编号<br/>
	**/
    private String channelCode;

    /**
	*渠道名称<br/>
	**/
    private String channelName;

    /**
	*客户手机号<br/>
	**/
    private String mobileNo;

    /**
	*处理结果<br/>
	**/
    private Integer status;

    /**
	*处理结果<br/>
	**/
    private String errorInfo;

    /**
	*是否已删除1删除 0正常<br/>
	**/
    private Integer df;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
	*单据源数据<br/>
	**/
    private String orderJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gxspurchorderinfo
     *
     * @mbggenerated Mon Jul 08 11:17:10 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录编号")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("所属商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("单据编号")
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    @Lable("渠道编号")
    public String getChannelCode() {
        return channelCode;
    }

    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    @Lable("渠道名称")
    public String getChannelName() {
        return channelName;
    }

    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    @Lable("客户手机号")
    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    @Lable("处理结果")
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Lable("处理结果")
    public String getErrorInfo() {
        return errorInfo;
    }

    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo == null ? null : errorInfo.trim();
    }

    @Lable("是否已删除1删除 0正常")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Lable("单据源数据")
    public String getOrderJson() {
        return orderJson;
    }

    public void setOrderJson(String orderJson) {
        this.orderJson = orderJson == null ? null : orderJson.trim();
    }
}