package com.dxh.mem.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class MemLabelDetail implements Serializable {
    /**
	*记录编号<br/>
	**/
    private Long id;

    /**
	*所属商家ID<br/>
	**/
    private Long vendorId;

    /**
	*标签编码<br/>
	**/
    private String labelCode;

    /**
	*标签名称<br/>
	**/
    private String labelName;

    /**
	*会员号<br/>
	**/
    private String memberCode;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*创建人<br/>
	**/
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memlabeldetail
     *
     * @mbggenerated Tue Sep 03 14:00:04 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录编号")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("所属商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("标签编码")
    public String getLabelCode() {
        return labelCode;
    }

    public void setLabelCode(String labelCode) {
        this.labelCode = labelCode == null ? null : labelCode.trim();
    }

    @Lable("标签名称")
    public String getLabelName() {
        return labelName;
    }

    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    @Lable("会员号")
    public String getMemberCode() {
        return memberCode;
    }

    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode == null ? null : memberCode.trim();
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("创建人")
    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}