package com.dxh.mem.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class MemMessage implements Serializable {
    /**
	*记录编号<br/>
	**/
    private Long id;

    /**
	*所属商家ID<br/>
	**/
    private Long vendorId;

    /**
	*会员号<br/>
	**/
    private String memberCode;

    /**
	*会员账号<br/>
	**/
    private String memPin;

    /**
	*是否已读(0-未读 1-已读)<br/>
	**/
    private Integer readOver;

    /**
	*消息标题<br/>
	**/
    private String messageTitle;

    /**
	*消息内容<br/>
	**/
    private String messageInfo;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
	*是否已删除1删除 0正常<br/>
	**/
    private Integer df;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memmessage
     *
     * @mbggenerated Wed Sep 18 16:20:58 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录编号")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("所属商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("会员号")
    public String getMemberCode() {
        return memberCode;
    }

    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode == null ? null : memberCode.trim();
    }

    @Lable("会员账号")
    public String getMemPin() {
        return memPin;
    }

    public void setMemPin(String memPin) {
        this.memPin = memPin == null ? null : memPin.trim();
    }

    @Lable("是否已读(0-未读 1-已读)")
    public Integer getReadOver() {
        return readOver;
    }

    public void setReadOver(Integer readOver) {
        this.readOver = readOver;
    }

    @Lable("消息标题")
    public String getMessageTitle() {
        return messageTitle;
    }

    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle == null ? null : messageTitle.trim();
    }

    @Lable("消息内容")
    public String getMessageInfo() {
        return messageInfo;
    }

    public void setMessageInfo(String messageInfo) {
        this.messageInfo = messageInfo == null ? null : messageInfo.trim();
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Lable("是否已删除1删除 0正常")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }
}