package com.dxh.mem.mapper;

import com.dxh.mem.entity.MemPrePay;

public interface MemPrePayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memprepay
     *
     * @mbggenerated Fri Sep 11 15:42:37 GMT+08:00 2020
     */
    int insert(MemPrePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memprepay
     *
     * @mbggenerated Fri Sep 11 15:42:37 GMT+08:00 2020
     */
    int insertSelective(MemPrePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memprepay
     *
     * @mbggenerated Fri Sep 11 15:42:37 GMT+08:00 2020
     */
    MemPrePay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memprepay
     *
     * @mbggenerated Fri Sep 11 15:42:37 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(MemPrePay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memprepay
     *
     * @mbggenerated Fri Sep 11 15:42:37 GMT+08:00 2020
     */
    int updateByPrimaryKey(MemPrePay record);
}