package com.dxh.mem.mapper;

import com.dxh.mem.entity.RebateRecord;

public interface RebateRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebaterecord
     *
     * @mbggenerated Fri Jul 31 16:08:09 GMT+08:00 2020
     */
    int insert(RebateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebaterecord
     *
     * @mbggenerated Fri Jul 31 16:08:09 GMT+08:00 2020
     */
    int insertSelective(RebateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebaterecord
     *
     * @mbggenerated Fri Jul 31 16:08:09 GMT+08:00 2020
     */
    RebateRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebaterecord
     *
     * @mbggenerated Fri Jul 31 16:08:09 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(RebateRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebaterecord
     *
     * @mbggenerated Fri Jul 31 16:08:09 GMT+08:00 2020
     */
    int updateByPrimaryKey(RebateRecord record);
}