package com.dxh.b2b.dao.mapper;

import com.dxh.b2b.domain.entity.MemSkuPrice;

public interface MemSkuPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memskuprice
     *
     * @mbggenerated Wed Nov 06 16:41:39 GMT+08:00 2019
     */
    int insert(MemSkuPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memskuprice
     *
     * @mbggenerated Wed Nov 06 16:41:39 GMT+08:00 2019
     */
    int insertSelective(MemSkuPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memskuprice
     *
     * @mbggenerated Wed Nov 06 16:41:39 GMT+08:00 2019
     */
    MemSkuPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memskuprice
     *
     * @mbggenerated Wed Nov 06 16:41:39 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(MemSkuPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memskuprice
     *
     * @mbggenerated Wed Nov 06 16:41:39 GMT+08:00 2019
     */
    int updateByPrimaryKey(MemSkuPrice record);
}