package com.dxh.wd.entity;

import java.io.Serializable;

public class RetailTemplateWithBLOBs extends RetailTemplate implements Serializable {
    /**
	*模版内容<br/>
	**/
    private String content;

    /**
	*门店商品编码<br/>
	**/
    private String skuCodes;

    /**
	*门店分类编码<br/>
	**/
    private String catCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table retailtemplate
     *
     * @mbggenerated Wed Jul 01 18:51:52 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("模版内容")
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Lable("门店商品编码")
    public String getSkuCodes() {
        return skuCodes;
    }

    public void setSkuCodes(String skuCodes) {
        this.skuCodes = skuCodes == null ? null : skuCodes.trim();
    }

    @Lable("门店分类编码")
    public String getCatCodes() {
        return catCodes;
    }

    public void setCatCodes(String catCodes) {
        this.catCodes = catCodes == null ? null : catCodes.trim();
    }
}