package com.dxh.base.dao.mapper;

import com.dxh.base.domain.entity.GxsStoreBindInfo;

public interface GxsStoreBindInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxsstorebindinfo
     *
     * @mbggenerated Tue Jul 30 14:41:29 GMT+08:00 2019
     */
    int insert(GxsStoreBindInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxsstorebindinfo
     *
     * @mbggenerated Tue Jul 30 14:41:29 GMT+08:00 2019
     */
    int insertSelective(GxsStoreBindInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxsstorebindinfo
     *
     * @mbggenerated Tue Jul 30 14:41:29 GMT+08:00 2019
     */
    GxsStoreBindInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxsstorebindinfo
     *
     * @mbggenerated Tue Jul 30 14:41:29 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(GxsStoreBindInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gxsstorebindinfo
     *
     * @mbggenerated Tue Jul 30 14:41:29 GMT+08:00 2019
     */
    int updateByPrimaryKey(GxsStoreBindInfo record);
}