package com.dxh.base.dao.mapper;

import com.dxh.base.domain.entity.ItemStatusChangeSet;

public interface ItemStatusChangeSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatuschangeset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int insert(ItemStatusChangeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatuschangeset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int insertSelective(ItemStatusChangeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatuschangeset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    ItemStatusChangeSet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatuschangeset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ItemStatusChangeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatuschangeset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int updateByPrimaryKey(ItemStatusChangeSet record);
}