package com.dxh.base.dao.mapper;

import com.dxh.base.domain.entity.ItemStatusConfig;

public interface ItemStatusConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusconfig
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int insert(ItemStatusConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusconfig
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int insertSelective(ItemStatusConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusconfig
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    ItemStatusConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusconfig
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ItemStatusConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusconfig
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int updateByPrimaryKey(ItemStatusConfig record);
}