package com.dxh.base.dao.mapper;

import com.dxh.base.domain.entity.ItemStatusOrderSet;

public interface ItemStatusOrderSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusorderset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int insert(ItemStatusOrderSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusorderset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int insertSelective(ItemStatusOrderSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusorderset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    ItemStatusOrderSet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusorderset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ItemStatusOrderSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemstatusorderset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    int updateByPrimaryKey(ItemStatusOrderSet record);
}