package com.dxh.base.dao.mapper;

import com.dxh.base.domain.entity.RevisedContractFee;

public interface RevisedContractFeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisedcontractfee
     *
     * @mbggenerated Mon Feb 10 16:52:42 GMT+08:00 2020
     */
    int insert(RevisedContractFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisedcontractfee
     *
     * @mbggenerated Mon Feb 10 16:52:42 GMT+08:00 2020
     */
    int insertSelective(RevisedContractFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisedcontractfee
     *
     * @mbggenerated Mon Feb 10 16:52:42 GMT+08:00 2020
     */
    RevisedContractFee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisedcontractfee
     *
     * @mbggenerated Mon Feb 10 16:52:42 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(RevisedContractFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisedcontractfee
     *
     * @mbggenerated Mon Feb 10 16:52:42 GMT+08:00 2020
     */
    int updateByPrimaryKey(RevisedContractFee record);
}