package com.dxh.base.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class GxsStoreBindInfo implements Serializable {
    /**
	*记录编号<br/>
	**/
    private Long id;

    /**
	*所属商家ID<br/>
	**/
    private Long vendorId;

    /**
	*门店编码<br/>
	**/
    private String storeCode;

    /**
	*门店名称<br/>
	**/
    private String storeName;

    /**
	*渠道编号<br/>
	**/
    private String channelCode;

    /**
	*渠道名称<br/>
	**/
    private String channelName;

    /**
	*客户手机号<br/>
	**/
    private String mobileNo;

    /**
	*创建日期<br/>
	**/
    private Date bindDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gxsstorebindinfo
     *
     * @mbggenerated Tue Jul 30 14:41:29 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录编号")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("所属商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("门店编码")
    public String getStoreCode() {
        return storeCode;
    }

    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    @Lable("门店名称")
    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    @Lable("渠道编号")
    public String getChannelCode() {
        return channelCode;
    }

    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    @Lable("渠道名称")
    public String getChannelName() {
        return channelName;
    }

    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    @Lable("客户手机号")
    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    @Lable("创建日期")
    public Date getBindDate() {
        return bindDate;
    }

    public void setBindDate(Date bindDate) {
        this.bindDate = bindDate;
    }
}