package com.dxh.base.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class ItemStatusChangeSet implements Serializable {
    /**
	*记录编号<br/>
	**/
    private Long id;

    /**
	*商家ID<br/>
	**/
    private Long vendorId;

    /**
	*生命周期<br/>
	**/
    private Integer itemStatus;

    /**
	*生命周期名称<br/>
	**/
    private String statusName;

    /**
	*转为正常 0不可转 1可转<br/>
	**/
    private Integer toNormal;

    /**
	*转为停购 0不可转 1可转<br/>
	**/
    private Integer toUnBuy;

    /**
	*转为停售 0不可转 1可转<br/>
	**/
    private Integer toUnSale;

    /**
	*转为淘汰 0不可转 1可转<br/>
	**/
    private Integer toUnUse;

    /**
	*转为归档 0不可转 1可转<br/>
	**/
    private Integer toForbidden;

    /**
	*转为新品 0不可转 1可转<br/>
	**/
    private Integer toNewApply;

    /**
	*转为新品审核 0不可转 1可转<br/>
	**/
    private Integer toNewApprove;

    /**
	*转为暂时禁销售 0不可转 1可转<br/>
	**/
    private Integer toTempUnSale;

    /**
	*转为季节商品 0不可转 1可转<br/>
	**/
    private Integer toSeasonItem;

    /**
	*备注<br/>
	**/
    private String memo;

    /**
	*是否已删除1删除 0正常<br/>
	**/
    private Integer df;

    /**
	*创建人<br/>
	**/
    private String crater;

    /**
	*修改人<br/>
	**/
    private String mender;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itemstatuschangeset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录编号")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("生命周期")
    public Integer getItemStatus() {
        return itemStatus;
    }

    public void setItemStatus(Integer itemStatus) {
        this.itemStatus = itemStatus;
    }

    @Lable("生命周期名称")
    public String getStatusName() {
        return statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }

    @Lable("转为正常 0不可转 1可转")
    public Integer getToNormal() {
        return toNormal;
    }

    public void setToNormal(Integer toNormal) {
        this.toNormal = toNormal;
    }

    @Lable("转为停购 0不可转 1可转")
    public Integer getToUnBuy() {
        return toUnBuy;
    }

    public void setToUnBuy(Integer toUnBuy) {
        this.toUnBuy = toUnBuy;
    }

    @Lable("转为停售 0不可转 1可转")
    public Integer getToUnSale() {
        return toUnSale;
    }

    public void setToUnSale(Integer toUnSale) {
        this.toUnSale = toUnSale;
    }

    @Lable("转为淘汰 0不可转 1可转")
    public Integer getToUnUse() {
        return toUnUse;
    }

    public void setToUnUse(Integer toUnUse) {
        this.toUnUse = toUnUse;
    }

    @Lable("转为归档 0不可转 1可转")
    public Integer getToForbidden() {
        return toForbidden;
    }

    public void setToForbidden(Integer toForbidden) {
        this.toForbidden = toForbidden;
    }

    @Lable("转为新品 0不可转 1可转")
    public Integer getToNewApply() {
        return toNewApply;
    }

    public void setToNewApply(Integer toNewApply) {
        this.toNewApply = toNewApply;
    }

    @Lable("转为新品审核 0不可转 1可转")
    public Integer getToNewApprove() {
        return toNewApprove;
    }

    public void setToNewApprove(Integer toNewApprove) {
        this.toNewApprove = toNewApprove;
    }

    @Lable("转为暂时禁销售 0不可转 1可转")
    public Integer getToTempUnSale() {
        return toTempUnSale;
    }

    public void setToTempUnSale(Integer toTempUnSale) {
        this.toTempUnSale = toTempUnSale;
    }

    @Lable("转为季节商品 0不可转 1可转")
    public Integer getToSeasonItem() {
        return toSeasonItem;
    }

    public void setToSeasonItem(Integer toSeasonItem) {
        this.toSeasonItem = toSeasonItem;
    }

    @Lable("备注")
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    @Lable("是否已删除1删除 0正常")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建人")
    public String getCrater() {
        return crater;
    }

    public void setCrater(String crater) {
        this.crater = crater == null ? null : crater.trim();
    }

    @Lable("修改人")
    public String getMender() {
        return mender;
    }

    public void setMender(String mender) {
        this.mender = mender == null ? null : mender.trim();
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}