package com.dxh.base.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class ItemStatusOrderSet implements Serializable {
    /**
	*记录编号<br/>
	**/
    private Long id;

    /**
	*商家ID<br/>
	**/
    private Long vendorId;

    /**
	*单据编码<br/>
	**/
    private String bizCode;

    /**
	*单据名称<br/>
	**/
    private String bizName;

    /**
	*正常 0不可用 1可用<br/>
	**/
    private Integer toNormal;

    /**
	*停购 0不可用 1可用<br/>
	**/
    private Integer unBuy;

    /**
	*停售 0不可用 1可用<br/>
	**/
    private Integer unSale;

    /**
	*淘汰 0不可用 1可用<br/>
	**/
    private Integer unUse;

    /**
	*归档 0不可用 1可用<br/>
	**/
    private Integer forbidden;

    /**
	*新品 0不可用 1可用<br/>
	**/
    private Integer newApply;

    /**
	*新品审核 0不可用 1可用<br/>
	**/
    private Integer newApprove;

    /**
	*暂时禁销售 0不可用 1可用<br/>
	**/
    private Integer tempUnSale;

    /**
	*季节商品 0不可用 1可用<br/>
	**/
    private Integer seasonItem;

    /**
	*备注<br/>
	**/
    private String memo;

    /**
	*是否已删除1删除 0正常<br/>
	**/
    private Integer df;

    /**
	*创建人<br/>
	**/
    private String crater;

    /**
	*修改人<br/>
	**/
    private String mender;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table itemstatusorderset
     *
     * @mbggenerated Wed Mar 11 10:30:55 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录编号")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("单据编码")
    public String getBizCode() {
        return bizCode;
    }

    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    @Lable("单据名称")
    public String getBizName() {
        return bizName;
    }

    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    @Lable("正常 0不可用 1可用")
    public Integer getToNormal() {
        return toNormal;
    }

    public void setToNormal(Integer toNormal) {
        this.toNormal = toNormal;
    }

    @Lable("停购 0不可用 1可用")
    public Integer getUnBuy() {
        return unBuy;
    }

    public void setUnBuy(Integer unBuy) {
        this.unBuy = unBuy;
    }

    @Lable("停售 0不可用 1可用")
    public Integer getUnSale() {
        return unSale;
    }

    public void setUnSale(Integer unSale) {
        this.unSale = unSale;
    }

    @Lable("淘汰 0不可用 1可用")
    public Integer getUnUse() {
        return unUse;
    }

    public void setUnUse(Integer unUse) {
        this.unUse = unUse;
    }

    @Lable("归档 0不可用 1可用")
    public Integer getForbidden() {
        return forbidden;
    }

    public void setForbidden(Integer forbidden) {
        this.forbidden = forbidden;
    }

    @Lable("新品 0不可用 1可用")
    public Integer getNewApply() {
        return newApply;
    }

    public void setNewApply(Integer newApply) {
        this.newApply = newApply;
    }

    @Lable("新品审核 0不可用 1可用")
    public Integer getNewApprove() {
        return newApprove;
    }

    public void setNewApprove(Integer newApprove) {
        this.newApprove = newApprove;
    }

    @Lable("暂时禁销售 0不可用 1可用")
    public Integer getTempUnSale() {
        return tempUnSale;
    }

    public void setTempUnSale(Integer tempUnSale) {
        this.tempUnSale = tempUnSale;
    }

    @Lable("季节商品 0不可用 1可用")
    public Integer getSeasonItem() {
        return seasonItem;
    }

    public void setSeasonItem(Integer seasonItem) {
        this.seasonItem = seasonItem;
    }

    @Lable("备注")
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    @Lable("是否已删除1删除 0正常")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建人")
    public String getCrater() {
        return crater;
    }

    public void setCrater(String crater) {
        this.crater = crater == null ? null : crater.trim();
    }

    @Lable("修改人")
    public String getMender() {
        return mender;
    }

    public void setMender(String mender) {
        this.mender = mender == null ? null : mender.trim();
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}