package com.dxh.base.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class RevisedContractFee implements Serializable {
    /**
	*记录编号<br/>
	**/
    private Long id;

    /**
	*商家ID<br/>
	**/
    private Long vendorId;

    /**
	*修正单号<br/>
	**/
    private String orderNo;

    /**
	*合同编号<br/>
	**/
    private String contractCode;

    /**
	*费用编码<br/>
	**/
    private String feeCode;

    /**
	*费用名称<br/>
	**/
    private String feeName;

    /**
	*扣款方式 1.固定金额 2.按进货金额比率 3.按销售金额比率 4.按销售保底金额比率<br/>
	**/
    private Integer chargeType;

    /**
	*扣款比率<br/>
	**/
    private Double chargeRate;

    /**
	*结算方式 1.一次 2.每月 3.半月 4.每周 5.季度 6.年 <br/>
	**/
    private Integer settleType;

    /**
	*金额<br/>
	**/
    private Double amount;

    /**
	*生效日期<br/>
	**/
    private Date effectiveDate;

    /**
	*失效日期<br/>
	**/
    private Date expiryDate;

    /**
	*是否已删除1删除 0正常<br/>
	**/
    private Integer df;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
	*备注<br/>
	**/
    private String memo;

    /**
	*票扣类型(1.票扣 2.非票扣)<br/>
	**/
    private Integer invoiceDeductionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table revisedcontractfee
     *
     * @mbggenerated Mon Feb 10 16:52:42 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录编号")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("修正单号")
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    @Lable("合同编号")
    public String getContractCode() {
        return contractCode;
    }

    public void setContractCode(String contractCode) {
        this.contractCode = contractCode == null ? null : contractCode.trim();
    }

    @Lable("费用编码")
    public String getFeeCode() {
        return feeCode;
    }

    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode == null ? null : feeCode.trim();
    }

    @Lable("费用名称")
    public String getFeeName() {
        return feeName;
    }

    public void setFeeName(String feeName) {
        this.feeName = feeName == null ? null : feeName.trim();
    }

    @Lable("扣款方式 1.固定金额 2.按进货金额比率 3.按销售金额比率 4.按销售保底金额比率")
    public Integer getChargeType() {
        return chargeType;
    }

    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    @Lable("扣款比率")
    public Double getChargeRate() {
        return chargeRate;
    }

    public void setChargeRate(Double chargeRate) {
        this.chargeRate = chargeRate;
    }

    @Lable("结算方式 1.一次 2.每月 3.半月 4.每周 5.季度 6.年 ")
    public Integer getSettleType() {
        return settleType;
    }

    public void setSettleType(Integer settleType) {
        this.settleType = settleType;
    }

    @Lable("金额")
    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    @Lable("生效日期")
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    @Lable("失效日期")
    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Lable("是否已删除1删除 0正常")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Lable("备注")
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    @Lable("票扣类型(1.票扣 2.非票扣)")
    public Integer getInvoiceDeductionType() {
        return invoiceDeductionType;
    }

    public void setInvoiceDeductionType(Integer invoiceDeductionType) {
        this.invoiceDeductionType = invoiceDeductionType;
    }
}