package com.dxh.mem.dao.mapper;

import com.dxh.mem.domain.entity.MemLabel;

public interface MemLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabel
     *
     * @mbggenerated Tue Sep 03 16:07:01 GMT+08:00 2019
     */
    int insert(MemLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabel
     *
     * @mbggenerated Tue Sep 03 16:07:01 GMT+08:00 2019
     */
    int insertSelective(MemLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabel
     *
     * @mbggenerated Tue Sep 03 16:07:01 GMT+08:00 2019
     */
    MemLabel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabel
     *
     * @mbggenerated Tue Sep 03 16:07:01 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(MemLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabel
     *
     * @mbggenerated Tue Sep 03 16:07:01 GMT+08:00 2019
     */
    int updateByPrimaryKey(MemLabel record);
}