package com.dxh.mem.dao.mapper;

import com.dxh.mem.domain.entity.MemLabelDetail;

public interface MemLabelDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabeldetail
     *
     * @mbggenerated Tue Sep 03 14:00:04 GMT+08:00 2019
     */
    int insert(MemLabelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabeldetail
     *
     * @mbggenerated Tue Sep 03 14:00:04 GMT+08:00 2019
     */
    int insertSelective(MemLabelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabeldetail
     *
     * @mbggenerated Tue Sep 03 14:00:04 GMT+08:00 2019
     */
    MemLabelDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabeldetail
     *
     * @mbggenerated Tue Sep 03 14:00:04 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(MemLabelDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table memlabeldetail
     *
     * @mbggenerated Tue Sep 03 14:00:04 GMT+08:00 2019
     */
    int updateByPrimaryKey(MemLabelDetail record);
}