package com.dxh.mem.dao.mapper;

import com.dxh.mem.domain.entity.PusherCount;

public interface PusherCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pushercount
     *
     * @mbggenerated Wed Apr 17 10:26:42 GMT+08:00 2019
     */
    int insert(PusherCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pushercount
     *
     * @mbggenerated Wed Apr 17 10:26:42 GMT+08:00 2019
     */
    int insertSelective(PusherCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pushercount
     *
     * @mbggenerated Wed Apr 17 10:26:42 GMT+08:00 2019
     */
    PusherCount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pushercount
     *
     * @mbggenerated Wed Apr 17 10:26:42 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(PusherCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pushercount
     *
     * @mbggenerated Wed Apr 17 10:26:42 GMT+08:00 2019
     */
    int updateByPrimaryKey(PusherCount record);
}