package com.dxh.base.entity;

import java.io.Serializable;
import java.util.Date;

public class ThirdUploadData implements Serializable {
    /**
	*记录ID<br/>
	**/
    private Long id;

    /**
	*数据来源 1 open平台<br/>
	**/
    private Integer source;

    /**
	*数据类型标识 接口编码<br/>
	**/
    private String menuCode;

    /**
	*消息编号 sourceCode 渠道编码<br/>
	**/
    private String sourceCode;

    /**
	*操作类型 0新增 1修改 2删除<br/>
	**/
    private Integer opType;

    /**
	*处理状态 0未处理 1已处理 2处理异常<br/>
	**/
    private Integer dealState;

    /**
	*消息发送时间<br/>
	**/
    private Date msgCreateDate;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
	*处理日期<br/>
	**/
    private Date dealDate;

    /**
	*是否已删除 1删除 0正常<br/>
	**/
    private Integer df;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirduploaddata
     *
     * @mbggenerated Sat Sep 26 10:31:21 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("数据来源 1 open平台")
    public Integer getSource() {
        return source;
    }

    public void setSource(Integer source) {
        this.source = source;
    }

    @Lable("数据类型标识 接口编码")
    public String getMenuCode() {
        return menuCode;
    }

    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    @Lable("消息编号 sourceCode 渠道编码")
    public String getSourceCode() {
        return sourceCode;
    }

    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    @Lable("操作类型 0新增 1修改 2删除")
    public Integer getOpType() {
        return opType;
    }

    public void setOpType(Integer opType) {
        this.opType = opType;
    }

    @Lable("处理状态 0未处理 1已处理 2处理异常")
    public Integer getDealState() {
        return dealState;
    }

    public void setDealState(Integer dealState) {
        this.dealState = dealState;
    }

    @Lable("消息发送时间")
    public Date getMsgCreateDate() {
        return msgCreateDate;
    }

    public void setMsgCreateDate(Date msgCreateDate) {
        this.msgCreateDate = msgCreateDate;
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Lable("处理日期")
    public Date getDealDate() {
        return dealDate;
    }

    public void setDealDate(Date dealDate) {
        this.dealDate = dealDate;
    }

    @Lable("是否已删除 1删除 0正常")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }
}