package com.dxh.base.entity;

import java.io.Serializable;

public class ThirdUploadDataWithBLOBs extends ThirdUploadData implements Serializable {
    /**
	*下发数据 json格式<br/>
	**/
    private String requestData;

    /**
	*处理异常原因 内部系统异常或者open返回json<br/>
	**/
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table thirduploaddata
     *
     * @mbggenerated Sat Sep 26 10:31:21 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("下发数据 json格式")
    public String getRequestData() {
        return requestData;
    }

    public void setRequestData(String requestData) {
        this.requestData = requestData == null ? null : requestData.trim();
    }

    @Lable("处理异常原因 内部系统异常或者open返回json")
    public String getFailReason() {
        return failReason;
    }

    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }
}