package com.dxh.mem.entity;

import java.io.Serializable;
import java.util.Date;

public class MemPrePay implements Serializable {
    /**
	*记录ID<br/>
	**/
    private Long id;

    /**
	*商家ID<br/>
	**/
    private Long vendorId;

    /**
	*订单号<br/>
	**/
    private String orderNo;

    /**
	*请求号<br/>
	**/
    private String batchNo;

    /**
	*机构编码<br/>
	**/
    private String organCode;

    /**
	*机构名称<br/>
	**/
    private String organName;

    /**
	*门店编码<br/>
	**/
    private String storeCode;

    /**
	*门店名称<br/>
	**/
    private String storeName;

    /**
	*POS机编码<br/>
	**/
    private String posCode;

    /**
	*操作员<br/>
	**/
    private String userName;

    /**
	*支付状态 0占用 1已完成 2已取消 支付占用一定时间未完成定时取消<br/>
	**/
    private Integer payStatus;

    /**
	*会员编号<br/>
	**/
    private String memNo;

    /**
	*会员手机号<br/>
	**/
    private String mobileNo;

    /**
	*会员名称<br/>
	**/
    private String memName;

    /**
	*支付类型 0储值 1储值卡 2积分 3优惠券 4返利金 5环保金<br/>
	**/
    private Integer payType;

    /**
	*支付方式对应的salePay支付编码<br/>
	**/
    private String payCode;

    /**
	*支付金额<br/>
	**/
    private Double payAmount;

    /**
	*储值卡号<br/>
	**/
    private String cardNo;

    /**
	*优惠券编码<br/>
	**/
    private String cpCode;

    /**
	*优惠券面值（可能大于实际支付金额）<br/>
	**/
    private Double cpValue;

    /**
	*使用积分<br/>
	**/
    private Double point;

    /**
	*是否删除<br/>
	**/
    private Integer df;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memprepay
     *
     * @mbggenerated Fri Sep 11 15:42:37 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("订单号")
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    @Lable("请求号")
    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    @Lable("机构编码")
    public String getOrganCode() {
        return organCode;
    }

    public void setOrganCode(String organCode) {
        this.organCode = organCode == null ? null : organCode.trim();
    }

    @Lable("机构名称")
    public String getOrganName() {
        return organName;
    }

    public void setOrganName(String organName) {
        this.organName = organName == null ? null : organName.trim();
    }

    @Lable("门店编码")
    public String getStoreCode() {
        return storeCode;
    }

    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    @Lable("门店名称")
    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    @Lable("POS机编码")
    public String getPosCode() {
        return posCode;
    }

    public void setPosCode(String posCode) {
        this.posCode = posCode == null ? null : posCode.trim();
    }

    @Lable("操作员")
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    @Lable("支付状态 0占用 1已完成 2已取消 支付占用一定时间未完成定时取消")
    public Integer getPayStatus() {
        return payStatus;
    }

    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    @Lable("会员编号")
    public String getMemNo() {
        return memNo;
    }

    public void setMemNo(String memNo) {
        this.memNo = memNo == null ? null : memNo.trim();
    }

    @Lable("会员手机号")
    public String getMobileNo() {
        return mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    @Lable("会员名称")
    public String getMemName() {
        return memName;
    }

    public void setMemName(String memName) {
        this.memName = memName == null ? null : memName.trim();
    }

    @Lable("支付类型 0储值 1储值卡 2积分 3优惠券 4返利金 5环保金")
    public Integer getPayType() {
        return payType;
    }

    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    @Lable("支付方式对应的salePay支付编码")
    public String getPayCode() {
        return payCode;
    }

    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    @Lable("支付金额")
    public Double getPayAmount() {
        return payAmount;
    }

    public void setPayAmount(Double payAmount) {
        this.payAmount = payAmount;
    }

    @Lable("储值卡号")
    public String getCardNo() {
        return cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    @Lable("优惠券编码")
    public String getCpCode() {
        return cpCode;
    }

    public void setCpCode(String cpCode) {
        this.cpCode = cpCode == null ? null : cpCode.trim();
    }

    @Lable("优惠券面值（可能大于实际支付金额）")
    public Double getCpValue() {
        return cpValue;
    }

    public void setCpValue(Double cpValue) {
        this.cpValue = cpValue;
    }

    @Lable("使用积分")
    public Double getPoint() {
        return point;
    }

    public void setPoint(Double point) {
        this.point = point;
    }

    @Lable("是否删除")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}