package com.dxh.order.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class GxsReconciliationInfo implements Serializable {
    /**
	*记录ID<br/>
	**/
    private Long id;

    /**
	*所属商家ID<br/>
	**/
    private Long vendorId;

    /**
	*机构编码<br/>
	**/
    private String organCode;

    /**
	*机构名称<br/>
	**/
    private String organName;

    /**
	*门店编码<br/>
	**/
    private String storeCode;

    /**
	*门店名称<br/>
	**/
    private String storeName;

    /**
	*订单编号<br/>
	**/
    private String orderNo;

    /**
	*支付单号<br/>
	**/
    private String orderPayNo;

    /**
	*支付平台流水号<br/>
	**/
    private String payInfo;

    /**
	*支付平台支付状态<br/>
	**/
    private Integer payPlatStatus;

    /**
	*订单状态<br/>
	**/
    private Integer orderStatus;

    /**
	*支付平台支付状态<br/>
	**/
    private Double payPlatAmount;

    /**
	*订单第三方支付金额<br/>
	**/
    private Double orderRealAmount;

    /**
	*对账来源/支付平台<br/>
	**/
    private String paySource;

    /**
	*处理状态 0 对账完成 1 对账异常<br/>
	**/
    private Integer dealStatus;

    /**
	*异常原因<br/>
	**/
    private String errorInfo;

    /**
	*订单创建时间<br/>
	**/
    private Date orderDate;

    /**
	*支付时间<br/>
	**/
    private Date payDate;

    /**
	*对账时间<br/>
	**/
    private Date createDate;

    /**
	*第三方对账文件订单信息<br/>
	**/
    private String reconciliationInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gxsreconciliationinfo
     *
     * @mbggenerated Thu Jan 31 15:56:03 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("所属商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("机构编码")
    public String getOrganCode() {
        return organCode;
    }

    public void setOrganCode(String organCode) {
        this.organCode = organCode == null ? null : organCode.trim();
    }

    @Lable("机构名称")
    public String getOrganName() {
        return organName;
    }

    public void setOrganName(String organName) {
        this.organName = organName == null ? null : organName.trim();
    }

    @Lable("门店编码")
    public String getStoreCode() {
        return storeCode;
    }

    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    @Lable("门店名称")
    public String getStoreName() {
        return storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    @Lable("订单编号")
    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    @Lable("支付单号")
    public String getOrderPayNo() {
        return orderPayNo;
    }

    public void setOrderPayNo(String orderPayNo) {
        this.orderPayNo = orderPayNo == null ? null : orderPayNo.trim();
    }

    @Lable("支付平台流水号")
    public String getPayInfo() {
        return payInfo;
    }

    public void setPayInfo(String payInfo) {
        this.payInfo = payInfo == null ? null : payInfo.trim();
    }

    @Lable("支付平台支付状态")
    public Integer getPayPlatStatus() {
        return payPlatStatus;
    }

    public void setPayPlatStatus(Integer payPlatStatus) {
        this.payPlatStatus = payPlatStatus;
    }

    @Lable("订单状态")
    public Integer getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    @Lable("支付平台支付状态")
    public Double getPayPlatAmount() {
        return payPlatAmount;
    }

    public void setPayPlatAmount(Double payPlatAmount) {
        this.payPlatAmount = payPlatAmount;
    }

    @Lable("订单第三方支付金额")
    public Double getOrderRealAmount() {
        return orderRealAmount;
    }

    public void setOrderRealAmount(Double orderRealAmount) {
        this.orderRealAmount = orderRealAmount;
    }

    @Lable("对账来源/支付平台")
    public String getPaySource() {
        return paySource;
    }

    public void setPaySource(String paySource) {
        this.paySource = paySource == null ? null : paySource.trim();
    }

    @Lable("处理状态 0 对账完成 1 对账异常")
    public Integer getDealStatus() {
        return dealStatus;
    }

    public void setDealStatus(Integer dealStatus) {
        this.dealStatus = dealStatus;
    }

    @Lable("异常原因")
    public String getErrorInfo() {
        return errorInfo;
    }

    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo == null ? null : errorInfo.trim();
    }

    @Lable("订单创建时间")
    public Date getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Lable("支付时间")
    public Date getPayDate() {
        return payDate;
    }

    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    @Lable("对账时间")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("第三方对账文件订单信息")
    public String getReconciliationInfo() {
        return reconciliationInfo;
    }

    public void setReconciliationInfo(String reconciliationInfo) {
        this.reconciliationInfo = reconciliationInfo == null ? null : reconciliationInfo.trim();
    }
}