package com.dxh.pay.entity;

import java.io.Serializable;
import java.util.Date;

public class AssetAccount implements Serializable {
    /**
	*记录ID<br/>
	**/
    private Long id;

    /**
	*所属商家ID<br/>
	**/
    private Long vendorId;

    /**
	*科目编码<br/>
	**/
    private String accountCode;

    /**
	*科目名称<br/>
	**/
    private String accountName;

    /**
	*父级编码<br/>
	**/
    private String parentCode;

    /**
	*结算方式编码<br/>
	**/
    private String settleTypeCode;

    /**
	*结算方式名称<br/>
	**/
    private String settleTypeName;

    /**
	*会计科目编码<br/>
	**/
    private String subjectCode;

    /**
	*账号<br/>
	**/
    private String account;

    /**
	*期初余额<br/>
	**/
    private Double beginning;

    /**
	*账号余额<br/>
	**/
    private Double amount;

    /**
	*是否启用（1.启用 0.停用）<br/>
	**/
    private Integer usable;

    /**
	*科目等级<br/>
	**/
    private Integer assetLevel;

    /**
	*是否叶子节点（1.是 0.否）<br/>
	**/
    private Integer leafNode;

    /**
	*是否系统科目（0,自动生成 1.用户添加）<br/>
	**/
    private Integer isInit;

    /**
	*是否账号（0.账号 1.账号类型）<br/>
	**/
    private Integer isAcount;

    /**
	*是否当前生效账套（1.是 0.否）<br/>
	**/
    private Integer isValid;

    /**
	*账套起始日期<br/>
	**/
    private Date fdbStartDate;

    /**
	*账套结束日期<br/>
	**/
    private Date fdbEndDate;

    /**
	*备注<br/>
	**/
    private String memo;

    /**
	*是否删除<br/>
	**/
    private Integer df;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
	*微信/支付宝 appID 酷享-apikey<br/>
	**/
    private String appID;

    /**
	*支付宝参数partnerId<br/>
	**/
    private String partnerId;

    /**
	*支付宝参数securityKey<br/>
	**/
    private String securityKey;

    /**
	*支付宝-公钥 酷享-密钥<br/>
	**/
    private String alipayPublicKey;

    /**
	*支付宝 私钥<br/>
	**/
    private String alipayPrivateKey;

    /**
	*微信参数appsecret <br/>
	**/
    private String appsecret;

    /**
	*微信 商户号<br/>
	**/
    private String mchId;

    /**
	*微信 API秘钥<br/>
	**/
    private String apiSecert;

    /**
	*微信 安全证书地址<br/>
	**/
    private String certPath;

    /**
	*微信 公众号原始ID<br/>
	**/
    private String originalId;

    /**
	*默认付款账户(0 否,1 是)<br/>
	**/
    private Integer defPayAct;

    /**
	*默认收款账户(0 否,1 是)<br/>
	**/
    private Integer defCollAct;

    /**
	*结算方式默认账户(0 否,1 是)<br/>
	**/
    private Integer defaultAccount;

    /**
	*授权模式下对应的支付表中开发者的AccountCode 或者 在线支付渠道编码<br/>
	**/
    private String isvAccountCode;

    /**
	*是否是isv:isvFlag 0代表账密模式，1代表isv模式<br/>
	**/
    private Integer isvFlag;

    /**
	*isv服务商名称<br/>
	**/
    private String isvAccountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table assetaccount
     *
     * @mbggenerated Thu Jun 11 14:20:42 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    @Lable("记录ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("所属商家ID")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("科目编码")
    public String getAccountCode() {
        return accountCode;
    }

    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    @Lable("科目名称")
    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    @Lable("父级编码")
    public String getParentCode() {
        return parentCode;
    }

    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    @Lable("结算方式编码")
    public String getSettleTypeCode() {
        return settleTypeCode;
    }

    public void setSettleTypeCode(String settleTypeCode) {
        this.settleTypeCode = settleTypeCode == null ? null : settleTypeCode.trim();
    }

    @Lable("结算方式名称")
    public String getSettleTypeName() {
        return settleTypeName;
    }

    public void setSettleTypeName(String settleTypeName) {
        this.settleTypeName = settleTypeName == null ? null : settleTypeName.trim();
    }

    @Lable("会计科目编码")
    public String getSubjectCode() {
        return subjectCode;
    }

    public void setSubjectCode(String subjectCode) {
        this.subjectCode = subjectCode == null ? null : subjectCode.trim();
    }

    @Lable("账号")
    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    @Lable("期初余额")
    public Double getBeginning() {
        return beginning;
    }

    public void setBeginning(Double beginning) {
        this.beginning = beginning;
    }

    @Lable("账号余额")
    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    @Lable("是否启用（1.启用 0.停用）")
    public Integer getUsable() {
        return usable;
    }

    public void setUsable(Integer usable) {
        this.usable = usable;
    }

    @Lable("科目等级")
    public Integer getAssetLevel() {
        return assetLevel;
    }

    public void setAssetLevel(Integer assetLevel) {
        this.assetLevel = assetLevel;
    }

    @Lable("是否叶子节点（1.是 0.否）")
    public Integer getLeafNode() {
        return leafNode;
    }

    public void setLeafNode(Integer leafNode) {
        this.leafNode = leafNode;
    }

    @Lable("是否系统科目（0,自动生成 1.用户添加）")
    public Integer getIsInit() {
        return isInit;
    }

    public void setIsInit(Integer isInit) {
        this.isInit = isInit;
    }

    @Lable("是否账号（0.账号 1.账号类型）")
    public Integer getIsAcount() {
        return isAcount;
    }

    public void setIsAcount(Integer isAcount) {
        this.isAcount = isAcount;
    }

    @Lable("是否当前生效账套（1.是 0.否）")
    public Integer getIsValid() {
        return isValid;
    }

    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    @Lable("账套起始日期")
    public Date getFdbStartDate() {
        return fdbStartDate;
    }

    public void setFdbStartDate(Date fdbStartDate) {
        this.fdbStartDate = fdbStartDate;
    }

    @Lable("账套结束日期")
    public Date getFdbEndDate() {
        return fdbEndDate;
    }

    public void setFdbEndDate(Date fdbEndDate) {
        this.fdbEndDate = fdbEndDate;
    }

    @Lable("备注")
    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    @Lable("是否删除")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    @Lable("微信/支付宝 appID 酷享-apikey")
    public String getAppID() {
        return appID;
    }

    public void setAppID(String appID) {
        this.appID = appID == null ? null : appID.trim();
    }

    @Lable("支付宝参数partnerId")
    public String getPartnerId() {
        return partnerId;
    }

    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    @Lable("支付宝参数securityKey")
    public String getSecurityKey() {
        return securityKey;
    }

    public void setSecurityKey(String securityKey) {
        this.securityKey = securityKey == null ? null : securityKey.trim();
    }

    @Lable("支付宝-公钥 酷享-密钥")
    public String getAlipayPublicKey() {
        return alipayPublicKey;
    }

    public void setAlipayPublicKey(String alipayPublicKey) {
        this.alipayPublicKey = alipayPublicKey == null ? null : alipayPublicKey.trim();
    }

    @Lable("支付宝 私钥")
    public String getAlipayPrivateKey() {
        return alipayPrivateKey;
    }

    public void setAlipayPrivateKey(String alipayPrivateKey) {
        this.alipayPrivateKey = alipayPrivateKey == null ? null : alipayPrivateKey.trim();
    }

    @Lable("微信参数appsecret ")
    public String getAppsecret() {
        return appsecret;
    }

    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    @Lable("微信 商户号")
    public String getMchId() {
        return mchId;
    }

    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    @Lable("微信 API秘钥")
    public String getApiSecert() {
        return apiSecert;
    }

    public void setApiSecert(String apiSecert) {
        this.apiSecert = apiSecert == null ? null : apiSecert.trim();
    }

    @Lable("微信 安全证书地址")
    public String getCertPath() {
        return certPath;
    }

    public void setCertPath(String certPath) {
        this.certPath = certPath == null ? null : certPath.trim();
    }

    @Lable("微信 公众号原始ID")
    public String getOriginalId() {
        return originalId;
    }

    public void setOriginalId(String originalId) {
        this.originalId = originalId == null ? null : originalId.trim();
    }

    @Lable("默认付款账户(0 否,1 是)")
    public Integer getDefPayAct() {
        return defPayAct;
    }

    public void setDefPayAct(Integer defPayAct) {
        this.defPayAct = defPayAct;
    }

    @Lable("默认收款账户(0 否,1 是)")
    public Integer getDefCollAct() {
        return defCollAct;
    }

    public void setDefCollAct(Integer defCollAct) {
        this.defCollAct = defCollAct;
    }

    @Lable("结算方式默认账户(0 否,1 是)")
    public Integer getDefaultAccount() {
        return defaultAccount;
    }

    public void setDefaultAccount(Integer defaultAccount) {
        this.defaultAccount = defaultAccount;
    }

    @Lable("授权模式下对应的支付表中开发者的AccountCode 或者 在线支付渠道编码")
    public String getIsvAccountCode() {
        return isvAccountCode;
    }

    public void setIsvAccountCode(String isvAccountCode) {
        this.isvAccountCode = isvAccountCode == null ? null : isvAccountCode.trim();
    }

    @Lable("是否是isv:isvFlag 0代表账密模式，1代表isv模式")
    public Integer getIsvFlag() {
        return isvFlag;
    }

    public void setIsvFlag(Integer isvFlag) {
        this.isvFlag = isvFlag;
    }

    @Lable("isv服务商名称")
    public String getIsvAccountName() {
        return isvAccountName;
    }

    public void setIsvAccountName(String isvAccountName) {
        this.isvAccountName = isvAccountName == null ? null : isvAccountName.trim();
    }
}