package com.dxh.b2b.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class MemSkuPrice implements Serializable {
    /**
	*主键<br/>
	**/
    private Long id;

    /**
	*商家编码<br/>
	**/
    private Long vendorId;

    /**
	*门店编码<br/>
	**/
    private String storeCode;

    /**
	*客户编码<br/>
	**/
    private String memPin;

    /**
	*会员号<br/>
	**/
    private String memberCode;

    /**
	*商品编码<br/>
	**/
    private String skuCode;

    /**
	*单位类型 0库存单位 1辅助单位一 2辅助单位二  3辅助单位三<br/>
	**/
    private Integer unitType;

    /**
	*辅助单位名称<br/>
	**/
    private String unit;

    /**
	*零售价<br/>
	**/
    private Double salePrice;

    /**
	*微店价<br/>
	**/
    private Double weiPrice;

    /**
	*分销价<br/>
	**/
    private Double distPrice;

    /**
	*进货价<br/>
	**/
    private Double purchasePrice;

    /**
	*批发价<br/>
	**/
    private Double wholesalePrice;

    /**
	*配送价<br/>
	**/
    private Double deliverPrice;

    /**
	*会员价<br/>
	**/
    private Double vipPrice;

    /**
	*会员价1<br/>
	**/
    private Double vipPrice1;

    /**
	*会员价2<br/>
	**/
    private Double vipPrice2;

    /**
	*删除标记 0正常 1已删除<br/>
	**/
    private Integer df;

    /**
	*创建日期<br/>
	**/
    private Date createDate;

    /**
	*修改日期<br/>
	**/
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table memskuprice
     *
     * @mbggenerated Wed Nov 06 16:41:39 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    @Lable("主键")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Lable("商家编码")
    public Long getVendorId() {
        return vendorId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    @Lable("门店编码")
    public String getStoreCode() {
        return storeCode;
    }

    public void setStoreCode(String storeCode) {
        this.storeCode = storeCode == null ? null : storeCode.trim();
    }

    @Lable("客户编码")
    public String getMemPin() {
        return memPin;
    }

    public void setMemPin(String memPin) {
        this.memPin = memPin == null ? null : memPin.trim();
    }

    @Lable("会员号")
    public String getMemberCode() {
        return memberCode;
    }

    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode == null ? null : memberCode.trim();
    }

    @Lable("商品编码")
    public String getSkuCode() {
        return skuCode;
    }

    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    @Lable("单位类型 0库存单位 1辅助单位一 2辅助单位二  3辅助单位三")
    public Integer getUnitType() {
        return unitType;
    }

    public void setUnitType(Integer unitType) {
        this.unitType = unitType;
    }

    @Lable("辅助单位名称")
    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    @Lable("零售价")
    public Double getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }

    @Lable("微店价")
    public Double getWeiPrice() {
        return weiPrice;
    }

    public void setWeiPrice(Double weiPrice) {
        this.weiPrice = weiPrice;
    }

    @Lable("分销价")
    public Double getDistPrice() {
        return distPrice;
    }

    public void setDistPrice(Double distPrice) {
        this.distPrice = distPrice;
    }

    @Lable("进货价")
    public Double getPurchasePrice() {
        return purchasePrice;
    }

    public void setPurchasePrice(Double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    @Lable("批发价")
    public Double getWholesalePrice() {
        return wholesalePrice;
    }

    public void setWholesalePrice(Double wholesalePrice) {
        this.wholesalePrice = wholesalePrice;
    }

    @Lable("配送价")
    public Double getDeliverPrice() {
        return deliverPrice;
    }

    public void setDeliverPrice(Double deliverPrice) {
        this.deliverPrice = deliverPrice;
    }

    @Lable("会员价")
    public Double getVipPrice() {
        return vipPrice;
    }

    public void setVipPrice(Double vipPrice) {
        this.vipPrice = vipPrice;
    }

    @Lable("会员价1")
    public Double getVipPrice1() {
        return vipPrice1;
    }

    public void setVipPrice1(Double vipPrice1) {
        this.vipPrice1 = vipPrice1;
    }

    @Lable("会员价2")
    public Double getVipPrice2() {
        return vipPrice2;
    }

    public void setVipPrice2(Double vipPrice2) {
        this.vipPrice2 = vipPrice2;
    }

    @Lable("删除标记 0正常 1已删除")
    public Integer getDf() {
        return df;
    }

    public void setDf(Integer df) {
        this.df = df;
    }

    @Lable("创建日期")
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Lable("修改日期")
    public Date getModifyDate() {
        return modifyDate;
    }

    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}